commercial: {
  month1: [
    {
      name: "BRONZE",
      month: "1 MONTH",
      price: "1499",
      speed: "100 Mbps",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "SILVER",
      month: "1 MONTH",
      price: "2999",
      speed: "150 Mbps",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "GOLD",
      month: "1 MONTH",
      price: "3999",
      speed: "250 Mbps",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "4 OTT APPS",
    },
    {
      name: "DIAMOND",
      month: "1 MONTH",
      price: "8999",
      speed: "300 Mbps",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
  ];
  month3: [
    {
      name: "BRONZE",
      month: "3 MONTH",
      Realprice: "1499",
      price: "1349",
      speed: "100 Mbps",
      Discount: "10% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "SILVER",
      month: "3 MONTH",
      Realprice: "2999",
      price: "2699",
      speed: "150 Mbps",
      Discount: "10% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "GOLD",
      month: "3 MONTH",
      price: "4499",
      Realprice: "4999",
      speed: "250 Mbps",
      Discount: "10% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "4 OTT APPS",
    },
    {
      name: "DIAMOND",
      month: "3 MONTH",
      Realprice: "8999",
      price: "8099",
      speed: "300 Mbps",
      Discount: "10% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
  ];
  month6: [
    {
      name: "BRONZE",
      month: "6 MONTH",
      Realprice: "1499",
      price: "1274",
      speed: "100 Mbps",
      Discount: "15% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "SILVER",
      month: "6 MONTH",
      Realprice: "2999",
      price: "2549",
      speed: "150 Mbps",
      Discount: "15% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "GOLD",
      month: "6 MONTH",
      Realprice: "4999",
      price: "4249",
      speed: "250 Mbps",
      Discount: "15% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "4 OTT APPS",
    },
    {
      name: "DIAMOND",
      month: "6 MONTH",
      Realprice: "7649",
      price: "8099",
      speed: "300 Mbps",
      Discount: "15% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
  ];
  month12: [
    {
      name: "BRONZE",
      month: "12 MONTH",
      Realprice: "1499",
      price: "1199",
      speed: "100 Mbps",
      Discount: "20% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "SILVER",
      month: "12 MONTH",
      Realprice: "2999",
      price: "2399",
      speed: "150 Mbps",
      Discount: "20% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
    {
      name: "GOLD",
      month: "12 MONTH",
      Realprice: "4999",
      price: "3999",
      speed: "250 Mbps",
      Discount: "20% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "4 OTT APPS",
    },
    {
      name: "DIAMOND",
      month: "12 MONTH",
      Realprice: "7649",
      price: "7199",
      speed: "300 Mbps",
      Discount: "20% OFF",
      cap: "0",
      data: "UNLIMITED DATA",
      connection: "0",
      isott: "",
    },
  ];
}
